### ISSUE TITLE
TypeError: show_res() got an unexpected keyword argument 'score'

### ISSUE THREAD

**Issue by kristiansimonato** [Daikenan/LTMU#26]
Hi, thanks for sharing your code. I’m trying to run the demo script to test the DiMP_LTMU tracker but this error occurs:

```
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /TBData2/kristian/.cache/torch/checkpoints/resnet50-19c8e357.pth
100%|██████████████████████████████████████| 97.8M/97.8M [00:01<00:00, 69.9MB/s]
0: yamaha: 1 /3143
1.36641526222229
Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    eval_tracking('demo', p=p)
  File "/media/TBData2/kristian_projects/conda_env/LTMU_demo/DiMP_LTMU/run_tracker.py", line 187, in eval_tracking
    run_seq_list(Dataset, p, sequence_list, data_dir)
  File "/media/TBData2/kristian_projects/conda_env/LTMU_demo/DiMP_LTMU/run_tracker.py", line 156, in run_seq_list
    region, score_map, iou, score_max, dis = tracker.tracking(image)
  File "/media/TBData2/kristian_projects/conda_env/LTMU_demo/DiMP_LTMU/Dimp_LTMU.py", line 526, in tracking
    frame_id=self.i, score=md_score, mask=mask)
TypeError: show_res() got an unexpected keyword argument 'score'
```

Has anyone encountered the same error or knows what the problem is? Thank you so much

**Comment by Daikenan** [comment]
The bug has been fixed, pls update the code.
