### ISSUE TITLE
Error for demo.py

### ISSUE THREAD

**Issue by nihuo76** [Daikenan/LTMU#5]
Hi, all the line work until the demo.py for which I got the following error:

Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    eval_tracking('demo', p=p)
  File "/home/hexin/LTMU/DiMP_LTMU/run_tracker.py", line 187, in eval_tracking
    run_seq_list(Dataset, p, sequence_list, data_dir)
  File "/home/hexin/LTMU/DiMP_LTMU/run_tracker.py", line 138, in run_seq_list
    tracker = Dimp_LTMU_Tracker(image, region, p=p, groundtruth=groundtruth)
  File "/home/hexin/LTMU/DiMP_LTMU/Dimp_LTMU.py", line 75, in __init__
    self.local_init(image, init_gt1)
  File "/home/hexin/LTMU/DiMP_LTMU/Dimp_LTMU.py", line 370, in local_init
    self.local_Tracker.initialize(image, init_box)
  File "/home/hexin/LTMU/DiMP_LTMU/pytracking/tracker/dimp/dimp.py", line 27, in initialize
    self.initialize_features()
  File "/home/hexin/LTMU/DiMP_LTMU/pytracking/tracker/dimp/dimp.py", line 17, in initialize_features
    self.params.net.initialize()
  File "/home/hexin/LTMU/DiMP_LTMU/pytracking/features/net_wrappers.py", line 41, in initialize
    super().initialize()
  File "/home/hexin/LTMU/DiMP_LTMU/pytracking/features/net_wrappers.py", line 34, in initialize
    self.load_network()
  File "/home/hexin/LTMU/DiMP_LTMU/pytracking/features/net_wrappers.py", line 28, in load_network
    self.net = load_network(self.net_path)
  File "/home/hexin/LTMU/DiMP_LTMU/pytracking/utils/loading.py", line 23, in load_network
    net, _ = ltr_loading.load_network(path_full, backbone_pretrained=False)
  File "./ltr/admin/loading.py", line 44, in load_network
    raise Exception('No matching checkpoint file found')
Exception: No matching checkpoint file found

Do you have any idea for the cause of this? Many thanks

**Comment by BruthYU** [comment]
Pytracking need checkpoint file for DiMP as /DiMP_LTMU/networks/dimp50.pth

**Comment by nihuo76** [comment]
> Pytracking need checkpoint file for DiMP as /DiMP_LTMU/networks/dimp50.pth

It works. Thanks a lot.
