### ISSUE TITLE
LTMU Training on custom objects

### ISSUE THREAD

**Issue by samohadid** [Daikenan/LTMU#54]
Dear Author:
Thanks for publishing the source code of Meta updater.
After referring to LTR and to read me in AtomMU Iam still confused about the dataset shape and the labels annotation needed. 
for testing I will train the superdimp on single class from the Lasot dataset.
after downloading Lasot dataset the data is separated in multiple files.
should I combine the data in one file? and should I change the annotation of the Lasot dataset?

**Comment by Daikenan** [comment]
The annotation of the original LaSOT dataset does not need any modification. 
The label of MU is generated based on the tracking result,the tracking results were classified based on IOU.

**Comment by samohadid** [comment]
@Daikenan 
thanks for your rapid response.
Iam using google colab for testing the framework. 
I installed the specific environment on colab. and I'm following instructions from file readme in ATOMMU. Moreover I changed the path of Lasot dataset in the file local_path.py
![image](https://user-images.githubusercontent.com/77728052/121354267-6502d200-c937-11eb-8f50-ff692e5f5ffd.png)

I downloaded a single category 'bicycle' of the dataset Lasot this is shape of data inside each folder
![image](https://user-images.githubusercontent.com/77728052/121354824-f07c6300-c937-11eb-8d90-ee8eda7a8101.png)

**The error **:

> 
> all data
> 
> Traceback (most recent call last):
>   File "/content/drive/MyDrive/LTMU/Super_DiMP_MU/run_tracker.py", line 91, in get_groundtruth
>     groundtruth = np.loadtxt(gt_dir, delimiter=',')
>   File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 981, in loadtxt
>     fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
>   File "/usr/local/lib/python3.7/dist-packages/numpy/lib/_datasource.py", line 269, in open
>     return ds.open(path, mode, encoding=encoding, newline=newline)
>   File "/usr/local/lib/python3.7/dist-packages/numpy/lib/_datasource.py", line 623, in open
>     raise IOError("%s not found." % path)
> OSError: /content/drive/MyDrive/Dateset/bicycle/bicycle-1/img/groundtruth.txt not found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_tracker.py", line 26, in <module>
>     eval_tracking('lasot', p=p, mode='all')
>   File "/content/drive/MyDrive/LTMU/Super_DiMP_MU/run_tracker.py", line 185, in eval_tracking
>     run_seq_list(Dataset, p, sequence_list, data_dir)
>   File "/content/drive/MyDrive/LTMU/Super_DiMP_MU/run_tracker.py", line 111, in run_seq_list
>     sequence_dir, groundtruth = get_groundtruth(Dataset, data_dir, video)
>   File "/content/drive/MyDrive/LTMU/Super_DiMP_MU/run_tracker.py", line 93, in get_groundtruth
>     groundtruth = np.loadtxt(gt_dir)
>   File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 981, in loadtxt
>     fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
>   File "/usr/local/lib/python3.7/dist-packages/numpy/lib/_datasource.py", line 269, in open
>     return ds.open(path, mode, encoding=encoding, newline=newline)
>   File "/usr/local/lib/python3.7/dist-packages/numpy/lib/_datasource.py", line 623, in open
>     raise IOError("%s not found." % path)
> OSError: /content/drive/MyDrive/Dateset/bicycle/bicycle-1/img/groundtruth.txt not found.

**Comment by qq1018408006** [comment]
@samohadid I guess you can find groundtruth.txt from Dataset/bicycle/bicycle-1 rather Dataset/bicycle/bicycle-1/img
